name: Deploy Backend to EC2

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy backend via SSH
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@13.54.211.80 <<EOF
            cd ~/E-commerce-Furniture/backend
            git pull origin main
            pm2 restart ecommerce-api || nohup node server.js &
          EOF
