name: Deploy Backend to EC2

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches: [main]

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/E-commerce-Furniture/backend
          git pull origin main
          npm install --production
          fuser -k 8080/tcp || true
          nohup node server.js > output.log 2>&1 &
          EOF
