name: Deploy React App to S3 + CloudFront

on:
    push:
        branches: [main]

defaults:
    run:
        working-directory: frontend
env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGL_OAUTH_REDIRECT_URI: ${{ secrets.REACT_APP_GOOGL_OAUTH_REDIRECT_URI }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: CI=false npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://serene-spaces-react --delete --exclude "productImages/*"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1Z202P1IAJPPI --paths "/*"