# .github/workflows/deploy-backend.yml

name: Deploy Backend to EC2

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@<YOUR_EC2_PUBLIC_IP> << 'EOF'
            cd ~/E-commerce-Furniture/backend
            git pull origin main
            pkill -f "node server.js" || true
            nohup node server.js > server.log 2>&1 &
          EOF
